### ISSUE TITLE
Docs...?

### ISSUE THREAD

**Issue by ConorOBrien-Foxx** [RikerW/Fuzzy-Octo-Guacamole#1]
I want to know how the fuzzy octo guacamole works!

**Comment by RikerW** [comment]
Dude, gimme a mo. This was created *today*. : P

**Comment by RikerW** [comment]
Plus, it is still a WIP.  Probably can do later today though.

**Comment by RikerW** [comment]
@ConorOBrien-Foxx  https://github.com/RikerW/Fuzzy-Octo-Guacamole/blob/master/README.md

**Comment by RikerW** [comment]
Has been updated.

**Comment by RikerW** [comment]
[Done](https://github.com/RikerW/Fuzzy-Octo-Guacamole/wiki/Commands).
